ptz:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    tilt:
      selector:
        select:
          options:
            - "DOWN"
            - "UP"
    pan:
      selector:
        select:
          options:
            - "LEFT"
            - "RIGHT"
    zoom:
      selector:
        select:
          options:
            - "ZOOM_IN"
            - "ZOOM_OUT"
    distance:
      default: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    speed:
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    continuous_duration:
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    preset:
      example: "1"
      default: "0"
      selector:
        text:
    move_mode:
      default: "RelativeMove"
      selector:
        select:
          options:
            - "AbsoluteMove"
            - "ContinuousMove"
            - "GotoPreset"
            - "RelativeMove"
            - "Stop"
ptz_move:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    pan:
      selector:
        select:
          options:
            - "LEFT"
            - "RIGHT"
    tilt:
      selector:
        select:
          options:
            - "DOWN"
            - "UP"
    distance:
      default: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    speed:
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
ptz_zoom:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    zoom:
      selector:
        select:
          options:
            - "ZOOM_IN"
            - "ZOOM_OUT"
    distance:
      default: 0.1
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    speed:
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
ptz_stop:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
ptz_continuous:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    pan:
      selector:
        select:
          options:
            - "LEFT"
            - "RIGHT"
    tilt:
      selector:
        select:
          options:
            - "DOWN"
            - "UP"
    zoom:
      selector:
        select:
          options:
            - "ZOOM_IN"
            - "ZOOM_OUT"
    speed:
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    continuous_duration:
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
    profile_token:
      selector:
        text:
ptz_absolute_steps:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    pan_steps:
      selector:
        number:
          min: 0
          max: 5000
          step: 1
    tilt_steps:
      selector:
        number:
          min: 0
          max: 2000
          step: 1
    zoom_steps:
      selector:
        number:
          min: 0
          max: 2000
          step: 1
    speed:
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    profile_token:
      selector:
        text:
goto_home:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
set_home:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
goto_preset:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    preset:
      example: "1"
      selector:
        text:
    speed:
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
set_preset:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    preset:
      selector:
        text:
    preset_name:
      required: true
      selector:
        text:
remove_preset:
  target:
    entity:
      integration: thingino_onvif
      domain: camera
  fields:
    preset:
      example: "1"
      selector:
        text:
    confirm:
      required: true
      example: "DELETE"
      selector:
        text:
